'use client'

import { useMemo, useState } from 'react'
import { Activity, ArrowLeft, BarChart3, Bell, CalendarDays, ChevronDown, ChevronRight, ClipboardCheck, FolderKanban, GitBranch,   Home as HomeIcon, LayoutGrid, Menu, Plus, Search, Settings, Target, Users, X } from 'lucide-react'

type View = 'home' | 'mbi' | 'mbo' | 'mapa' | 'pdca' | 'projetos' | 'usuarios' | 'organograma'
type Status = 'green' | 'yellow' | 'red'

const perspectives = [
  { key: 'FINANCIAL_RESILIENCE', label: 'Financial resilience', color: '#2f9e44' },
  { key: 'BUSINESS_GROWTH', label: 'Business growth', color: '#2474d4' },
  { key: 'EFFICIENCY', label: 'Efficiency', color: '#e08b22' },
  { key: 'CUSTOMER', label: 'Customer', color: '#7b4bc4' },
  { key: 'EMPLOYEE', label: 'Employee', color: '#159b9d' },
  { key: 'STABLE_BUSINESS', label: 'Stable business', color: '#6b7280' },
]
const indicators = [
  { code: 'FIN-001', name: 'CAPEX overall', perspective: 'FINANCIAL_RESILIENCE', owner: 'Mauro Iwamura', target: 'R$ 48,0 mi', result: 'R$ 45,2 mi', status: 'green' as Status, parent: null },
  { code: 'FIN-001.1', name: 'CAPEX planejamento industrial', perspective: 'FINANCIAL_RESILIENCE', owner: 'Cassiano Souza', target: 'R$ 28,0 mi', result: 'R$ 27,4 mi', status: 'green' as Status, parent: 'FIN-001' },
  { code: 'FIN-001.2', name: 'CAPEX engenharia de produto', perspective: 'FINANCIAL_RESILIENCE', owner: 'Gabrielle Leocádio', target: 'R$ 20,0 mi', result: 'R$ 17,8 mi', status: 'yellow' as Status, parent: 'FIN-001' },
  { code: 'FIN-002', name: 'Receita líquida', perspective: 'FINANCIAL_RESILIENCE', owner: 'Helio Ninomiya', target: 'R$ 210 mi', result: 'R$ 214 mi', status: 'green' as Status, parent: null },
  { code: 'GRO-001', name: 'Market share South America', perspective: 'BUSINESS_GROWTH', owner: 'Valmir Fernandez', target: '22,0%', result: '20,8%', status: 'yellow' as Status, parent: null },
  { code: 'EFF-001', name: 'Entrega no prazo', perspective: 'EFFICIENCY', owner: 'Alexandre Silva', target: '95%', result: '91%', status: 'red' as Status, parent: null },
  { code: 'CUS-001', name: 'NPS clientes', perspective: 'CUSTOMER', owner: 'Jacqueline Araujo', target: '75 pts', result: '78 pts', status: 'green' as Status, parent: null },
  { code: 'EMP-001', name: 'Horas de treinamento', perspective: 'EMPLOYEE', owner: 'Leticia Silva', target: '420 h', result: '395 h', status: 'yellow' as Status, parent: null },
  { code: 'STA-001', name: 'Índice de continuidade operacional', perspective: 'STABLE_BUSINESS', owner: 'Nohara Ken', target: '99,5%', result: '99,8%', status: 'green' as Status, parent: null },
]
const months = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
const users = ['Cassiano Souza','Emanuel Caxias','Nicolle Gluck','Alexandre Silva','Gabrielle Leocádio','Jacqueline Araujo','Leticia Silva','Nicolas Cavalcante','Nohara Ken','Mauro Iwamura']

function StatusDot({ status }: { status: Status }) { return <span className={`status-dot ${status}`} /> }
function Btn({ children, primary = false, onClick }: { children: React.ReactNode; primary?: boolean; onClick?: () => void }) { return <button onClick={onClick} className={primary ? 'btn primary' : 'btn'}>{children}</button> }

function Welcome({ onStart }: { onStart: () => void }) { return <div className="welcome"><div className="wave-brand"><strong>YAMAHA</strong><span>Management Business System</span></div><div className="welcome-card"><div><span className="eyebrow">STRATEGIC MANAGEMENT</span><h1>Gestão por<br /><b>estratégia</b></h1><p>Conecte metas, indicadores, projetos e pessoas em uma única visão de negócio.</p><Btn primary onClick={onStart}>Começar <ChevronRight size={16} /></Btn></div><div className="welcome-illustration"><BarChart3 size={110} /><Target size={76} /></div></div></div> }

function Sidebar({ view, setView }: { view: View; setView: (v: View) => void }) { const items: [View,string,React.ElementType][] = [['home','Início',HomeIcon],['mbi','MBI',Activity],['mbo','MBO',Target],['mapa','Mapa de indicadores',GitBranch],['pdca','Soluções de problemas',ClipboardCheck],['projetos','Projetos',FolderKanban],['usuarios','Usuários',Users],['organograma','Organograma',GitBranch]]; return <aside className="side"><div className="side-logo">Y<span>MBS</span></div><nav>{items.map(([key,label,Icon]) => <button key={key} className={view === key ? 'active' : ''} onClick={() => setView(key)} title={label}><Icon size={20} /><span>{label}</span></button>)}</nav><div className="side-bottom"><button onClick={() => setView('usuarios')}><Settings size={20} /><span>Configurações</span></button><button><Bell size={20} /><span>Alertas</span></button></div></aside> }
function Top({ view, setView }: { view: View; setView: (v: View) => void }) { return <header className="top"><button className="mobile-menu"><Menu size={19} /></button><div className="top-title">MBS <span>/ {view === 'home' ? 'Home' : view.toUpperCase()}</span></div><div className="top-actions"><div className="top-search"><Search size={15} /><input placeholder="Pesquisar" /></div><span className="year">2026 <ChevronDown size={14} /></span><button className="avatar" onClick={() => setView('usuarios')}>EC</button><div><b>Eduardo Caxias</b><small>Administrador</small></div></div></header> }

function Home({ setView }: { setView: (v: View) => void }) { return <div className="home-view"><div className="home-hero"><span className="eyebrow">BEM-VINDO AO MBS</span><h1>Olá, Eduardo.<br /><b>O que vamos alcançar hoje?</b></h1><p>Tenha uma visão rápida da performance e acesse suas rotinas estratégicas.</p></div><div className="quick-grid"><button onClick={() => setView('mbi')}><Activity /><b>Acompanhamento MBI</b><small>Veja seus indicadores mensais</small></button><button onClick={() => setView('mbo')}><Target /><b>MBO / PLR</b><small>Metas e resultados semestrais</small></button><button onClick={() => setView('mapa')}><GitBranch /><b>Mapa estratégico</b><small>Explore relações de causa e efeito</small></button><button onClick={() => setView('pdca')}><ClipboardCheck /><b>Soluções de problemas</b><small>Acompanhe PDCA e ações</small></button></div><div className="home-panels"><section className="card"><h2>Resumo da organização</h2><div className="metrics"><div><strong>72%</strong><span>Indicadores na meta</span></div><div><strong>08</strong><span>Projetos em andamento</span></div><div><strong>05</strong><span>Pontos de atenção</span></div></div></section><section className="card"><h2>Próximas atividades</h2>{['Fechamento MBI · 18 Dez','Comitê de resultados · 20 Dez','Revisão de metas · 23 Dez'].map(x => <div className="activity-row" key={x}><CalendarDays size={15} />{x}<ChevronRight size={14} /></div>)}</section></div></div> }

function MBI() { return <Screen title="Acompanhamento MBI" subtitle="Acompanhe os indicadores atribuídos ao seu usuário no ciclo mensal."><div className="toolbar"><span>2026 <ChevronDown size={14} /></span><span>Dezembro <ChevronDown size={14} /></span><Btn>Exportar</Btn></div><section className="table-card"><div className="table-title"><h2>Indicadores de Eduardo Caxias</h2><span>6 / 9 indicadores preenchidos</span></div><div className="table-scroll"><table><thead><tr><th>Indicador</th><th>Polaridade</th><th>Unidade</th><th>Meta</th><th>Resultado</th><th>% Meta</th><th>Status</th></tr></thead><tbody>{indicators.slice(0,6).map((i, index) => <tr key={i.code}><td><b>{i.name}</b><small>{i.code} · {i.perspective}</small></td><td>↑</td><td>{i.name.includes('share') ? '%' : 'R$'}</td><td>{i.target}</td><td>{i.result}</td><td>{[94,98,104,89,103,94][index]}%</td><td><StatusDot status={i.status} /></td></tr>)}</tbody></table></div></section><section className="card status-board"><h2>Status do ciclo</h2><div><span>Entregas<strong>4</strong></span><span>Pontos de atenção<strong>2</strong></span><span>Próximos passos<strong>3</strong></span></div></section></Screen> }

function MBO() { return <Screen title="MBO / PLR" subtitle="Acompanhamento semestral das metas individuais e corporativas."><div className="half-tabs"><button className="selected">2026 · 1º semestre</button><button>2026 · 2º semestre</button></div><section className="table-card"><div className="table-title"><h2>2026 GOALS · 01st half</h2><strong>91,93%</strong></div><div className="table-scroll"><table><thead><tr><th>Indicador</th><th>Meta</th><th>Resultado</th><th>% Meta</th><th>Peso</th><th>Score</th></tr></thead><tbody>{indicators.map(i => <tr key={i.code}><td><b>{i.name}</b><small>{i.owner}</small></td><td>{i.target}</td><td>{i.result}</td><td>{i.status === 'green' ? '100%' : i.status === 'yellow' ? '94%' : '89%'}</td><td>10%</td><td><StatusDot status={i.status} /></td></tr>)}</tbody></table></div></section><section className="project-strip"><b>PROJETOS</b><span>Inventory Control & Risk Governance Stabilization 2026</span><StatusDot status="green" /></section></Screen> }

function MapView() { const [mode, setMode] = useState<'lista'|'hierarquia'>('lista'); const [expanded, setExpanded] = useState<string[]>(['FIN-001']); const toggle = (code:string) => setExpanded(x => x.includes(code) ? x.filter(v => v !== code) : [...x, code]); return <Screen title="Mapa de indicadores" subtitle="Navegue pelas perspectivas estratégicas e relações entre indicadores."><div className="map-toolbar"><div className="half-tabs"><button className={mode==='lista'?'selected':''} onClick={() => setMode('lista')}>Lista por perspectiva</button><button className={mode==='hierarquia'?'selected':''} onClick={() => setMode('hierarquia')}>Mapa hierárquico</button></div><Btn primary><Plus size={15} /> Novo indicador</Btn></div>{mode === 'lista' ? <div className="perspective-grid">{perspectives.map(p => <section className="perspective card" key={p.key}><div className="perspective-head" style={{borderColor:p.color}}><span style={{background:p.color}} /><div><b>{p.label}</b><small>{indicators.filter(i=>i.perspective===p.key).length} indicadores</small></div></div>{indicators.filter(i=>i.perspective===p.key).map(i => <div className="map-row" key={i.code}><StatusDot status={i.status} /><div><b>{i.name}</b><small>{i.code} · {i.owner}</small></div><span>{i.result}</span><ChevronRight size={14}/></div>)}</section>)}</div> : <div className="hierarchy"><div className="root-node">Estratégia Yamaha · 2026 <small>Mapa corporativo</small></div><div className="hierarchy-line" /> <div className="hierarchy-grid">{perspectives.map(p => <div className="tree-branch" key={p.key}><div className="branch-node" style={{borderTopColor:p.color}}>{p.label}</div>{indicators.filter(i=>i.perspective===p.key).map(i => <div className={`child-node ${i.parent?'nested':''}`} key={i.code} onClick={() => i.parent && toggle(i.code)}><StatusDot status={i.status}/><span>{i.name}<small>{i.code} · {i.result}</small></span>{i.parent ? <ChevronDown size={14}/> : null}</div>)}</div>)}</div></div>}</Screen> }

function PDCA() { const [selected, setSelected] = useState(0); const pdcas = [{title:'Índice de ocupação de aeronaves abaixo da meta', owner:'Adriano Rodrigues', status:'Em execução', progress:39, indicator:'EFF-001'}, {title:'Atraso na liberação de pedidos de cliente', owner:'Gabrielle Leocádio', status:'Em identificação', progress:18, indicator:'CUS-001'}, {title:'Desvio de CAPEX engenharia de produto', owner:'Cassiano Souza', status:'Em análise', progress:62, indicator:'FIN-001.2'}]; const item=pdcas[selected]; return <Screen title="Soluções de problemas" subtitle="Acompanhe ações corretivas e preventivas para indicadores fora da meta."><div className="pdca-list">{pdcas.map((p,i)=><button key={p.title} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><StatusDot status={i===0?'red':i===1?'yellow':'green'}/><div><b>{p.title}</b><small>PDCA · {p.indicator} · {p.owner}</small></div><span>{p.status}</span><ChevronRight size={16}/></button>)}</div><section className="pdca-detail card"><div className="detail-banner"><span>PDCA</span><h2>{item.title}</h2><small>{item.status} · Relatado por {item.owner} · Indicador {item.indicator}</small></div><div className="progress-line"><span>Progresso das ações</span><b>{item.progress}%</b><div><i style={{width:`${item.progress}%`}} /></div></div><div className="pdca-columns">{[['PLAN','Identificação do problema','Descrever o desvio, causas possíveis e meta esperada.'],['DO','Ações em andamento','Executar contramedidas e registrar evidências.'],['CHECK','Verificação','Comparar resultado real contra a meta do indicador.'],['ACT','Padronização','Consolidar aprendizados e prevenir recorrência.']].map(([tag,title,desc])=><div key={tag}><strong>{tag}</strong><h3>{title}</h3><p>{desc}</p><Btn>{tag==='DO'?'Adicionar ação':'Abrir etapa'}</Btn></div>)}</div></section></Screen> }

function Projetos() { const [open, setOpen] = useState(false); const projects=[['Inventory Control & Risk Governance Stabilization','Cassiano Souza','72%','12 mar 2026','FIN-001 · EFF-001'],['Digital Customer Journey 2026','Jacqueline Araujo','48%','28 abr 2026','CUS-001 · GRO-001'],['Academia de Líderes Yamaha','Leticia Silva','34%','30 jun 2026','EMP-001']]; return <Screen title="Projetos" subtitle="Conecte responsáveis, marcos, indicadores, atividades e cronogramas."><div className="toolbar"><span>Todos os projetos <ChevronDown size={14}/></span><Btn primary onClick={()=>setOpen(true)}><Plus size={15}/> Novo projeto</Btn></div><div className="project-grid">{projects.map(([name,owner,progress,date,links])=><section className="card project-card" key={name}><div className="project-top"><FolderKanban size={18}/><StatusDot status={progress==='72%'?'green':'yellow'}/></div><h2>{name}</h2><p>Responsável: <b>{owner}</b></p><div className="project-progress"><span><b>{progress}</b> concluído</span><span>{date}</span></div><div className="bar"><i style={{width:progress}} /></div><div className="project-meta"><span>Marcos <b>4</b></span><span>Atividades <b>12</b></span><span>Indicadores <b>{links.split('·').length}</b></span></div><small>{links}</small><Btn onClick={()=>setOpen(true)}>Abrir projeto <ChevronRight size={14}/></Btn></section>)}</div>{open&&<div className="modal-wrap"><div className="modal card"><button className="close" onClick={()=>setOpen(false)}><X size={18}/></button><span className="eyebrow">NOVO PROJETO</span><h2>Configurar projeto estratégico</h2>{['Nome do projeto','Responsável','Data de início','Data de término','Indicadores envolvidos'].map(x=><label key={x}>{x}<input placeholder={`Informe ${x.toLowerCase()}`} /></label>)}<Btn primary onClick={()=>setOpen(false)}>Salvar projeto</Btn></div></div>}</Screen> }

function Usuarios() { const [selected,setSelected]=useState(0); return <Screen title="Team Management" subtitle="Configure reporting structure and delegation permissions."><div className="users-layout"><section className="user-list card"><div className="user-search"><Search size={16}/><input placeholder="Search employees..." /></div>{users.map((u,i)=><button className={selected===i?'selected':''} key={u} onClick={()=>setSelected(i)}><span className="user-avatar">{u.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{u}</b><small>{i%2?'INDUSTRIAL PLANNING':'INFORMATION TECHNOLOGY'}</small></div>{i<5&&<em>Admin</em>}</button>)}</section><section className="user-detail card"><div className="profile-head"><span className="profile-avatar">{users[selected].split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><h2>{users[selected]}</h2><small>INDUSTRIAL PLANNING · STRATEGY ANALYST</small></div></div><div className="form-grid">{['Name','Department','Position','Report manager'].map(x=><label key={x}>{x} *<input defaultValue={x==='Name'?users[selected]:x==='Department'?'INDUSTRIAL PLANNING':x==='Position'?'STRATEGY ANALYST':'Nohara Ken'} /></label>)}</div><div className="org-preview"><span>Nohara Ken<small>Executive director</small></span><span className="selected-person">{users[selected]}<small>Strategy analyst</small></span>{users.slice(1,5).map(u=><span key={u}>{u}<small>Industrial planning</small></span>)}</div><Btn primary>Salvar alterações</Btn></section></div></Screen> }
function Organograma() { const nodes=[['Mauro Iwamura','President'],['Nohara Ken','Executive director'],['Cassiano Souza','Industrial planning supervisor'],['Emanuel Caxias','Systems analyst'],['Nicolle Gluck','Administrative assistant'],['Alexandre Silva','Junior specialist'],['Gabrielle Leocádio','Planning analyst']]; return <Screen title="Organograma" subtitle="Visualize a estrutura de reporte e navegue pela empresa."><div className="org-toolbar"><div className="user-search"><Search size={16}/><input placeholder="Procurar pessoas" /></div><Btn>Minha estrutura</Btn><Btn>Empresa inteira</Btn></div><div className="org-canvas"><div className="org-root"><span className="profile-avatar">MI</span><b>{nodes[0][0]}</b><small>{nodes[0][1]}</small></div><div className="org-connector"/><div className="org-level"><div className="org-manager"><span className="profile-avatar">NK</span><b>{nodes[1][0]}</b><small>{nodes[1][1]}</small></div><div className="org-children">{nodes.slice(2).map(n=><div className="org-person" key={n[0]}><span className="profile-avatar">{n[0].split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{n[0]}</b><small>{n[1]}</small></div><ChevronRight size={15}/></div>)}</div></div></div></Screen> }
function Screen({ title, subtitle, children }: { title:string; subtitle:string; children:React.ReactNode }) { return <div><div className="screen-head"><div><span className="eyebrow">MANAGEMENT BUSINESS SYSTEM</span><h1>{title}</h1><p>{subtitle}</p></div><div className="head-buttons"><Btn><CalendarDays size={15}/> 2026 <ChevronDown size={14}/></Btn><Btn primary><Plus size={15}/> Adicionar</Btn></div></div>{children}</div> }

export default function Page() { const [started,setStarted]=useState(false); const [view,setView]=useState<View>('home'); const content = view==='home'?<Home setView={setView}/>:view==='mbi'?<MBI/>:view==='mbo'?<MBO/>:view==='mapa'?<MapView/>:view==='pdca'?<PDCA/>:view==='projetos'?<Projetos/>:view==='usuarios'?<Usuarios/>:<Organograma/>; if(!started) return <Welcome onStart={()=>setStarted(true)}/>; return <main className="app-shell"><Sidebar view={view} setView={setView}/><div className="workspace"><Top view={view} setView={setView}/><div className="content">{content}</div></div></main> }
